import Head from 'next/head'
import Footer from '../components/Layout/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>    
      <Footer /> 
    </div>
  )
}
